CREATE TABLE `forma_pgto` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB
ROW_FORMAT=DEFAULT;

INSERT INTO `forma_pgto` VALUES (1,'DINHEIRO'),(2,'CARTÃO'),(3,'PIX'),(4,'BANCO');
ALTER TABLE `ctpag` ADD COLUMN `forma_pgto_id` INTEGER DEFAULT NULL;
ALTER TABLE `ctpag` ADD COLUMN `total_ordem`   INTEGER DEFAULT NULL;